pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    cd BCDV4033/Calculator
                    ls
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'I am testing'
            }
        }
    }
}
