apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ethereum-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ethereum-sa
  namespace: default
roleRef:
  kind: Role
  name: ethereum-role
  apiGroup: rbac.authorization.k8s.io
