name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: Calculator

      - name: Run tests
        run: npm test
        working-directory: Calculator

      - name: Build project
        run: npm run build
        working-directory: Calculator

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: Calculator/dist/

      - name: Setup API Key
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Display Name
        run: echo "Your Name"
